### PR TITLE
Add support for ASN1BMPString

### PR DESCRIPTION
**Pull request by Ephenodrom**
While parsing a CSR I came across a not yet supported ASN1 object. It seems not to be used quite often, but here is the implementation of it with some unit tests.

### CODE REVIEW

**Comment by Ephenodrom** [comment]
@mwcw 
I hope you are doing well! It would be nice to have this synced up on pub.dev within the next days :)

**Comment by Ephenodrom** [comment]
@mwcw 
Any update on this :) ?

**Comment by Ephenodrom** [comment]
@dghgit @mwcw 
Any update on this ? Would be great to get this synced on pub.dev.

**Comment by mwcw** [comment]
Thanks,

This will sync up shortly.

**Pull request closed without merging**
