### PR TITLE
add dart2wasm support

### LINKED ISSUE #221: Support dart2wasm
To reproduce:

- have the dart2wasm compiler
- import this package into a main.dart with void main
- run dart compile wasm main.dart
Output:

../../../AppData/Local/Pub/Cache/hosted/pub.dev/pointycastle-3.7.4/lib/src/platform_check/node_crypto.dart:5:1: Error: JS interop library 'package:js/js.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js.dart';
^
../../../AppData/Local/Pub/Cache/hosted/pub.dev/pointycastle-3.7.4/lib/src/platform_check/web.dart:5:1: Error: JS interop library 'package:js/js.dart' can't be imported when compiling to Wasm.
Try using 'dart:js_interop' or 'dart:js_interop_unsafe' instead.
import 'package:js/js.dart';
^

This library impacts the popular `package:image`. I've filed a matching report with them [here](https://github.com/brendan-duncan/image/issues/610).

### PR DESCRIPTION
**Pull request by konsultaner**
fixes #221

- [x] `Random.secure()` needs to be fixed by the sdk team

### CODE REVIEW

**Comment by konsultaner** [comment]
@Ephenodrom Do you see any issues with this?

**Comment by Ephenodrom** [comment]
@konsultaner I am not very familiar with Dart / Flutter on web, due to i only use it on CLI or for apps running on different operating systems, therefore my knowledge is limited but I see no problem with the PR. I will check the unit tests and see if they are good.

**Comment by Ephenodrom** [comment]
@konsultaner There are several tests that fail with the following error : "Failed to load "test/stream/eax_test.dart": The "buf" argument must be an instance of ArrayBuffer or ArrayBufferView. Received an instance of Array".

Please take a look. The tests are run with "dart run test -p node" and use the latest dart version 3.3.1

**Comment by konsultaner** [comment]
> The "buf" argument must be an instance of ArrayBuffer or ArrayBufferView. Received an instance of Array

@Ephenodrom I'm on it. I forgot to test it with node. seems a bit tricky, but I know why the tests fail.

**Comment by konsultaner** [comment]
@Ephenodrom I fixed it. Could you try again?

I just also want to notice that you might want to change `dart pub run` to just `dart run` in your CI script since it is depricated. if the next version of dart it released you might also want to add a test with `--platform chrome -c dart2wasm` to also validate the [wasm support](https://docs.flutter.dev/platform-integration/web/wasm). For some reason `--platform node -c dart2wasm` is not supported yet. I guess this is due to a missing wasm-gc support in older node versions. I think the current latest node version should supprt it.

**Comment by Ephenodrom** [comment]
@konsultaner This looks good so far. I already merged the PR in the origin repo. 

When I run the test for the node environment via "dart run test -p node ", there are some tests that fail. Is this intended at the moment?

**Comment by konsultaner** [comment]
@Ephenodrom no it is not intended. It should not fail at all. Thats strange. All tests were successful when I tested it locally. Ill have another look at it.

**Comment by konsultaner** [comment]
@Ephenodrom I checked everything again and ran `dart test -p node` on a node `v16.20.1` with dart on `3.3.1`. That resulted in:

image

What errors do you get?

**Comment by Ephenodrom** [comment]
@konsultaner 
Ok strange, I tried it with node version v20.6.1 and the latest version v21.7.1.

I receive for example the following error :

```txt
00:28 +119 -1: loading test/key_generators/rsa_key_generator_test.dart [E]
  Failed to load "test/key_generators/rsa_key_generator_test.dart": Value of "this" must be of type nullish or must be the global object
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/js_string.dart 202:5   global.cryptoThisCheck
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/math_patch.dart 253:9  _JSSecureRandom._JSSecureRandom
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/math_patch.dart 251:3  <fn>
  org-dartlang-sdk:///lib/_internal/js_runtime/lib/math_patch.dart 74:30  PlatformWeb.PlatformWeb
  package:pointycastle/src/platform_check/web.dart 15:3                   <fn>
  package:pointycastle/src/platform_check/web.dart 65:39                  _generationTests.<fn>.<fn>.<fn>
```

**Comment by konsultaner** [comment]
@Ephenodrom I tried it again on node 21.7.1, dart 3.1.1 on linux with the command:

     dart run test -p node

And the same result, all tests run perfectly. 

Could you please start the workflow to have the github ci test it too?

image

**Comment by Ephenodrom** [comment]
@konsultaner The checks look good so far. I have contacted someone from bouncycastle to sync the repository, if this is done I will create a new release on pub.dev. I keep you updated.

**Comment by Ephenodrom** [comment]
@konsultaner The changes are now live on pub.dev with version 3.8.0. Thank you very much for the PR.

**Comment by sgehrman** [comment]
It's including the js package, so it's not WASM compatible.  Please fix.

[dart:js_interop](https://api.dart.dev/stable/dart-js_interop), which replaces package:js and dart:js

**Comment by konsultaner** [comment]
@sgehrman I can't find either of the old packages in the current code. Please link the code, so I can fix it.

**Pull request merged**
