### PR TITLE
Enable and fix a number of lints

### PR DESCRIPTION
**Pull request by kevmoo**

### CODE REVIEW

**Comment by kevmoo** [comment]
@Ephenodrom ?

**Comment by Ephenodrom** [comment]
@kevmoo 
I will take a look at it within the next days!

**Comment by Ephenodrom** [comment]
@kevmoo Looks good so far. Will ask someone from Bouncycastle to sync the repositories and then create a new release on pub.dev.

**Comment by kevmoo** [comment]
@Ephenodrom – remember, everytime you squash merge an angel gets its wings. 😄

**Pull request merged**
