### PR TITLE
Finalize README for release

### PR DESCRIPTION
**Pull request by AKushWarrior**

### CODE REVIEW

**Comment by AKushWarrior** [comment]
@mwcw This is non-breaking and ready for merge.

On a side note, is there any progress on a potential release?

**Comment by mwcw** [comment]
> @mwcw This is non-breaking and ready for merge.
> 
> On a side note, is there any progress on a potential release?

Sort of, we have had a discussion about it.

At the moment we are doing FIPS related activities but next week sounds like a good time to do it.

MW

**Comment by AKushWarrior** [comment]
Cool thanks for the update.

> At the moment we are doing FIPS related activities but next week sounds like a good time to do it.

Will check back in next week.

**Comment by mwcw** [comment]
Hi 

Thanks Aditya, much appreciated!

This will sync up to github shortly.

Thanks!

MW

**Comment by AKushWarrior** [comment]
Cool, happy to help as always!

**Pull request closed without merging**
