### PR TITLE
Adding ASN1Lib

### PR DESCRIPTION
**Pull request by Ephenodrom**
This is some work for #35 to add a ASN1Lib to this package.

The first step is to add the basic classes that represent the ASN1 primitives.

The implementation consists of a base class and a seperate class for each ASN1 primitive. Each class, has a seperate test file to test the encoding and decoding.

These are all BER tags supported by the [java](https://github.com/bcgit/bc-java/blob/master/core/src/main/java/org/bouncycastle/asn1/BERTags.java) bouncy castle project and the ASN1Lib package :
- [x] BOOLEAN
- [x] INTEGER
- [x] BIT_STRING
- [x] OCTET_STRING
- [x] NULL
- [x] OBJECT_IDENTIFIER
- [x] ENUMERATED
- [x] UTF8_STRING
- [x] SEQUENCE
- [x] SET
- [x] PRINTABLE_STRING
- [x] IA5_STRING
- [x] UTC_TIME

### CODE REVIEW

**Comment by mwcw** [comment]
Hi,

I have not looked at the code yet but I had a talk with @dghbc about the ASN1 library and we concluded that initially the most important primitives to support are: SEQUENCE, INTEGER, OBJECT IDENTIFIER, SET. For INTEGER and OBJECT IDENTIFIER there is only one possible binary encoding. However SEQUENCE will need to ultimately handle BER/DER/DL. 

With DER encoded SEQUENCE and INTEGER the api will be able to start handling DSA/ECDSA signatures.

We really appreciate you doing this work, it is backbone work and it is important because once the API can start to support standard ASN1 encoded messages it opens it up to more users and significantly increases utility well beyond being a library of transformations.

Thanks you very much!

MW

**Comment by dghgit** [comment]
With IA5String, Octet String, UTC Time, Printable String, would you be able to add DER and DL equivalents as sub-classes with encode methods on them? DL and BER will start to rear their heads once things like SETs and constructed octet strings get added, you should be able to save a lot of effort by taking them into account now. We could have saved a lot of work in the Java APIs for Bouncy Castle if we'd properly appreciated this when we started. If you have any questions about what I've said, please feel free to ask. ASN.1 is both simple and complicated...

**Comment by Ephenodrom** [comment]
@dghgit / @mwcw 
Now all ASN1 objects are defined. The next step is to create an ASN1 parser. After this is finished, this library holds the same functionality as the ASN1Lib package (https://pub.dev/packages/asn1lib). So as I understand it,if this is done every current ASN1Object will supports BER encoding. 

The next step after that would be to integrate the DER and DL encoding. But I am not familiar with that. We will see if I can handle this too after finishing the above mentioned steps.

I also took a look at the Bouncy Castle Java project and yes I think we will too need nearly the same setup with a seperate DER and DL class for some ASN1Objects.

As a background information : I am not that familiar with cryptographie and I try to increase my knowledge in this area. That's why I want to contribute to this project. Learning by doing and reading some stuff :)

**Comment by dghgit** [comment]
If you're looking for source material to read a good place to start is:

https://www.bouncycastle.org/asn1_layman_93.txt

By way of further info, with the encoding, BER encompasses DL and DER. DL encompasses DER. 

With DER everything is definite length encoded, but there are also specific rules about how things get encoded - this is important to take into account as signatures and MACs are almost always calculated on DER encoded data. Sets, for example, must be sorted.

In the case of DL (definite length) everything is definite length encoded but DER rules are not followed (in that sense this is just BER without indefinite length encodings). Messages do often contain definite length objects such as octet strings which are also constructed (so an octet string is actually composed of what looks like a sequence definite length octet strings), all strings can have a constructed encoding, but in BC's case the only place we've run into them is with octet strings. BER with indefinite length always uses constructed encodings but terminates the construction with the bytes (0, 0). In the case of indefinite length we've run into it with sequence, set, and octet string again.

**Comment by mwcw** [comment]
Hi,

Thanks you very much for this.

I have merged it, I had to make a minor change to a test and I added a "all_test" file to collect asn1 related tests rather than import each file in the "all_tests_web.dart" file.

We really appreciate you doing this!

Thanks,

MW

**Comment by Ephenodrom** [comment]
@mwcw 
I added an ASN1Parser so now this package has the same functionality as the ASN1Lib. So for me the first step is done and I think we can close this PR.

We should then update the corresponding issue on Github, write down the current status and discuss how to proceed with DER and DL encoding.
Maybe someone else will take this over, because I first have to read and understand this document : https://www.bouncycastle.org/asn1_layman_93.txt

Please check out the Travis build. Every test is passed and it failed due to 

```bash
0.21s$ pana --verbosity compact --source path .
Could not find an option named "verbosity".
``` 

Regards

**Comment by Ephenodrom** [comment]
@dghgit / @mwcw 

I took a look at the ASN1 guide by layman and now I have a question on how we should handle contructed types.

In the guide there is an example of a constructed IA5String : 

```
36 13 16 05 74 65 73 74 31 16 01 40 16 07 72 73 61 2e 63 6f 6d
```
That is printed out like this by https://lapo.it/asn1js/: 

```
IA5String test1@rsa.com
  IA5String test1
  IA5String @
  IA5String rsa.com
```
So for my understanding this is just a Sequence with another tag where each child has the same type.

Should we handle constructed primitives as a ASN1Sequence, as the same class or as a seperate class ?

Example : 

```dart

var bytes = Uint8List.fromList([0x36,0x13,0x16,0x05,0x74,0x65,0x73,0x74,0x31,0x16,0x01,0x40,0x16,0x07,0x72,0x73,0x61,0x2e,0x63,0x6f,0x6d]);
var parser = ASN1Parser(bytes);
// Option 1
var sequence = parser.nextObject() as ASN1Sequence;
sequence.elements;
// Option 2
var Ia5String = parser.nextObject() as ASN1IA5String;
Ia5String.elements;
// Option 3
var constructedIa5String = parser.nextObject() as ASN1ConstructedIA5String;
Ia5String.elements;
```

- Option 1 : Return an ASN1Sequence
- Option 2 : Return an ASN1IA5String and add the elements field that is a List<ASN1Object>
- Option 2 : Create a seperate class ASN1ConstructedIA5String and use it in this case.

Any thoughts on this  ?

**Comment by AKushWarrior** [comment]
From an OO perspective, the 3rd option is clearly the best to me: ASN1ConstructedIA5String has all the same functionality as an ASN1IA5String plus an extra subset. I think that you should extend the ASN1IA5String class in the ASN1ConstructedIA5String class so a user can use ASN1IA5String as a function parameter without worrying about the distinction between the two classes.

With that said, I'm not 100% on the details here, so I might have misinterpreted something. Let me know...

**Comment by dghgit** [comment]
You want it to appear as an ASN1IA5String to the user and be returned from the parser as such. You (and your users) will go insane otherwise. What you do "under the hood" is largely up to you.

With only a few exceptions, such as INTEGER and OBJECT IDENTIFIER, a constructed type can appear anywhere a non-constructed primitive type can and it can also be indefinite or definite length encoded. In the BC Java API the BEROctetString captures this flexibility with the DEROctetString representing the definite length encoding (which in this case is also the DER encoding), both of these extend ASN1OctetString which is the "universal type" that people usually program to. so they don't have to worry about whether the encoding was constructed or not.

Note: it must always be possible to generate the encodings DER equivalent from the returned object, signatures, macs and digests are usually (pretty well always) calculated from the DER encoding. There is usually no requirement to encode the structures going into the signature, mac, or digest, as DER when storing it though so it is not unusual for BER to appear in a structure that is signed on the assumption that anyone verifying the signature will convert the encodings to DER before attempting to verify it.

**Comment by Ephenodrom** [comment]
| ASN1 Type  | Decode From  | Encode To  |
|---|---|---|
| BOOLEAN  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| INTEGER  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| BIT_STRING  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| OCTET_STRING  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br>  |
| NULL  | * DER :heavy_check_mark:<br>* BER Long Length Form:heavy_check_mark:  | * DER :heavy_check_mark:<br>*BER Long Length Form:heavy_check_mark: |
| OBJECT_IDENTIFIER  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| ENUMERATED  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| UTF8_STRING  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| SEQUENCE  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| SET  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br>|
| PRINTABLE_STRING  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |
| IA5_STRING  | * DER :heavy_check_mark:<br>* BER Constructed:heavy_check_mark:<br>* BER Long Length Form:heavy_check_mark:    | * DER :heavy_check_mark:<br>* BER Constructed:heavy_check_mark:<br>*BER Long Length Form:heavy_check_mark: |
| UTC_TIME  | * DER :heavy_check_mark:<br> | * DER :heavy_check_mark:<br> |

**Comment by penhorwood** [comment]
I looked into the pana --verbosity flag.  It was removed in version 0.14.0.  Here are the details https://pub.dev/packages/pana/changelog

The "official version" of pana on pub.dev and github seem to differ.

**Comment by mwcw** [comment]
> I looked into the pana --verbosity flag. It was removed in version 0.14.0. Here are the details https://pub.dev/packages/pana/changelog
> 
> The "official version" of pana on pub.dev and github seem to differ.

Thanks!

I am just catching up on pull requests, it will go through with those.

MW

**Comment by mwcw** [comment]
Hi,

Sorry about this, I am getting a couple of test failures locally.

I really appreciate the effort that is going into the ASN1 Library.

Thanks.

MW

```
00:05 +397 -1: Test encode BER Constructed Indefinite Length [E]
  Bad state: Too few elements
  dart:typed_data-patch/typed_data_patch.dart 408:7                _TypedIntListMixin.setRange
  package:pointycastle/asn1/asn1_object.dart 103:20                ASN1Object.encode
  package:pointycastle/asn1/primitives/asn1_ia5_string.dart 94:18  ASN1IA5String.encode
  test/asn1/primitives/asn1_ia5_string_test.dart 406:20            main.<fn>
  package:test/src/backend/declarer.dart 168:27                    Declarer.test.<fn>.<fn>.<fn>
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1118:19                                     _CustomZone.registerBinaryCallback
  dart:async-patch/async_patch.dart 88:23                          _asyncErrorWrapperHelper
  package:test/src/backend/invoker.dart                            Invoker.waitForOutstandingCallbacks.<fn>
  dart:async/zone.dart 1184:13                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 1619:10                                     _runZoned
  dart:async/zone.dart 1539:10                                     runZoned
  package:test/src/backend/invoker.dart 247:5                      Invoker.waitForOutstandingCallbacks
  package:test/src/backend/declarer.dart 166:33                    Declarer.test.<fn>.<fn>
  dart:async/zone.dart 1184:13                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 1619:10                                     _runZoned
  dart:async/zone.dart 1539:10                                     runZoned
  package:test/src/backend/declarer.dart 165:13                    Declarer.test.<fn>
  package:test/src/backend/invoker.dart 403:30                     Invoker._onRun.<fn>.<fn>.<fn>.<fn>
  dart:async/future.dart 176:37                                    new Future.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15     StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48     StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1180:38                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 979:7                                       _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                     _CustomZone.bindCallbackGuarded.<fn>
  package:stack_trace/src/stack_zone_specification.dart 206:15     StackZoneSpecification._run
  package:stack_trace/src/stack_zone_specification.dart 116:48     StackZoneSpecification._registerCallback.<fn>
  dart:async/zone.dart 1184:13                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 1003:23                                     _CustomZone.bindCallback.<fn>
  dart:async-patch/timer_patch.dart 23:15                          Timer._createTimer.<fn>
  dart:isolate-patch/timer_impl.dart 398:19                        _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                         _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                     _RawReceivePortImpl._handleMessage
  ===== asynchronous gap ===========================
  dart:async/zone.dart 1101:19                                     _CustomZone.registerCallback
  dart:async/zone.dart 1018:22                                     _CustomZone.bindCallbackGuarded
  dart:async/timer.dart 54:45                                      new Timer
  dart:async/timer.dart 91:9                                       Timer.run
  dart:async/future.dart 174:11                                    new Future
  package:test/src/backend/invoker.dart 402:11                     Invoker._onRun.<fn>.<fn>.<fn>
  dart:async/zone.dart 1184:13                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 1619:10                                     _runZoned
  dart:async/zone.dart 1539:10                                     runZoned
  package:test/src/backend/invoker.dart 389:9                      Invoker._onRun.<fn>.<fn>
  package:test/src/backend/invoker.dart 441:15                     Invoker._guardIfGuarded
  package:test/src/backend/invoker.dart 388:7                      Invoker._onRun.<fn>
  package:stack_trace/src/chain.dart 102:24                        Chain.capture.<fn>
  dart:async/zone.dart 1184:13                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 1619:10                                     _runZoned
  dart:async/zone.dart 1539:10                                     runZoned
  package:stack_trace/src/chain.dart 100:12                        Chain.capture
  package:test/src/backend/invoker.dart 387:11                     Invoker._onRun
  package:test/src/backend/live_test_controller.dart 185:11        LiveTestController._run
  package:test/src/backend/live_test_controller.dart 40:31         _LiveTest.run
  dart:async/future.dart 202:37                                    new Future.microtask.<fn>
  dart:async/zone.dart 1180:38                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 979:7                                       _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                     _CustomZone.bindCallbackGuarded.<fn>
  dart:async/zone.dart 1184:13                                     _rootRun
  dart:async/zone.dart 1077:19                                     _CustomZone.run
  dart:async/zone.dart 979:7                                       _CustomZone.runGuarded
  dart:async/zone.dart 1019:23                                     _CustomZone.bindCallbackGuarded.<fn>
  dart:async/schedule_microtask.dart 43:21                         _microtaskLoop
  dart:async/schedule_microtask.dart 52:5                          _startMicrotaskLoop
  dart:isolate-patch/isolate_patch.dart 118:13                     _runPendingImmediateCallback
  dart:isolate-patch/timer_impl.dart 405:11                        _Timer._runTimers
  dart:isolate-patch/timer_impl.dart 429:5                         _Timer._handleMessage
  dart:isolate-patch/isolate_patch.dart 168:12                     _RawReceivePortImpl._handleMessage
  
00:05 +397 -1: Test named constructor fromBytes
00:05 +398 -1: Test encode
00:05 +399 -1: Test named constructor fromBytes
00:05 +400 -1: Test encode DER
00:05 +401 -1: Test encode BER Long Form Length
00:05 +402 -1: Test named constructor fromBytes
00:05 +403 -1: Test encode
00:05 +404 -1: Test named constructor fromComponentString
00:05 +405 -1: Test named constructor fromBytes
00:05 +406 -1: Test encode
00:05 +407 -1: Test named constructor fromBytes
00:05 +408 -1: Test encode
00:05 +409 -1: Test named constructor fromBytes
00:05 +410 -1: Test encode
00:05 +411 -1: Test named constructor fromBytes
00:05 +412 -1: Test encode
00:05 +413 -1: Test named constructor fromBytes
00:05 +414 -1: Test encode
00:05 +415 -1: Test named constructor fromBytes
00:05 +416 -1: Test encode
00:05 +417 -1: Some tests failed.

Unhandled exception:
Dummy exception to set exit code.
00:08 +20 -1: test/asn1/primitives/asn1_ia5_string_test.dart: Test encode BER Constructed Indefinite Length [E]                                                                                                                   
  Bad state: Too few elements
  dart:typed_data                                                  _TypedIntListMixin.setRange
  package:pointycastle/asn1/asn1_object.dart 103:20                ASN1Object.encode
  package:pointycastle/asn1/primitives/asn1_ia5_string.dart 94:18  ASN1IA5String.encode
  test/asn1/primitives/asn1_ia5_string_test.dart 406:20            main.<fn>
  
00:15 +58 -2: test/asn1/asn1_all_test.dart: Test encode BER Constructed Indefinite Length [E]                                                                                                                                     
  Bad state: Too few elements
  dart:typed_data                                                  _TypedIntListMixin.setRange
  package:pointycastle/asn1/asn1_object.dart 103:20                ASN1Object.encode
  package:pointycastle/asn1/primitives/asn1_ia5_string.dart 94:18  ASN1IA5String.encode
  test/asn1/primitives/asn1_ia5_string_test.dart 406:20            main.<fn>
  
01:12 +449 -2: Some tests failed.                                                                                                                                                                                                 
meganwoods@tyche-3265 pc-dart % dart --version
Dart VM version: 2.8.4 (stable) (Wed Jun 3 12:26:04 2020 +0200) on "macos_x64"

```

**Comment by Ephenodrom** [comment]
@mwcw / @penhorwood 
This should be done now! I did the following things : 

- Created all ASN1 objects to handle DER / BER Constructed / BER Long Length Form / BER Padded /BER Constructed Indefinite Lengt, depending on the objects. I used the  https://www.bouncycastle.org/asn1_layman_93.txt as a guide to achieve this.
- Created a unit test for each encoding / decoding, using the examples from https://www.bouncycastle.org/asn1_layman_93.txt
- Created an ASN1Parser class to parse a given bytes. Covered it with some unit tests, like parsing an x509 certificate pem.
- Created a small tutorial for the ASN1 stuff.

All checks have passed and there are no merge conflicts.

Hint : If the ASN1 stuff is available via this package I will change my Basic Utils package (https://github.com/Ephenodrom/Dart-Basic-Utils) to use this instead of the asn1lib. The Basic Utils package has also a lot of unit tests that cover x509 decoding and other stuff.

**Comment by penhorwood** [comment]
Cool.  Thanks.

**Comment by AKushWarrior** [comment]
@mwcw This is tested and ready for merging.

**Comment by mwcw** [comment]
Hi,

This has been merged and will be published in the next release.

We are grateful for the work you have done here and it will contribute significantly to the API moving forward!

Thanks again.

MW

**Pull request closed without merging**
